import React from "react";
import styles from "./Terms-condition.module.css";
const PrivacyPolicy = () => {
  return (
    <div className={styles.privacyContainer}>
      <header className={styles.header}>
        <h1>Dubai Car Rental Privacy Policy | Policy Exclusive to Caryyati | Caryyati</h1>
        <nav className={styles.nav}>
          <a href="/">Home</a>
          <a href="/privacy-policy">Dubai Car Rental Privacy Policy | Policy Exclusive to Caryyati |</a>
        </nav>
      </header>
      <main className={styles.mainContent}>
        <h2>Caryyati's Privacy Policy</h2>
        <p>Last updated: April 04, 2021</p>
        <p>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
        </p>

        <h3>Interpretation and Definitions</h3>
        <p>
          The words in which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in the plural.
        </p>

        <h4>Definitions</h4>
        <p>For the purposes of this Privacy Policy:</p>
        <ul className={styles.definitionList}>
          <li>
            <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Caryyati, Dubai, UAE.
          </li>
          <li>
            <strong>Service</strong> refers to the Website or the Application or both.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.
          </li>
          <li>
            <strong>Cookies</strong> are small files stored on Your device.
          </li>
        </ul>
        <hr />

        <h3>Collecting and Using Your Personal Data</h3>
        <p>
          We may collect several types of information for various purposes to provide and improve our Service to you.
        </p>

        <h4>Types of Data Collected</h4>
        <p>
          <strong>Personal Data</strong>: While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You.
        </p>
        <p>
          <strong>Usage Data</strong>: We may also collect information on how the Service is accessed and used.
        </p>

        <h3>Use of Your Personal Data</h3>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul className={styles.useList}>
          <li>To provide and maintain our Service</li>
          <li>To notify You about changes to our Service</li>
          <li>To allow You to participate in interactive features</li>
        </ul>
        <hr />
      </main>
    </div>
 
 
 

  );
};

export default PrivacyPolicy;