'use client';

import React, { useState } from 'react';
import styles from './PrivacyPolicy.module.css';
import Footer from '../../components/foorter/Footer';

const PrivacyPolicy = () => {
  const [activeSection, setActiveSection] = useState('introduction');

  const sections = [
    { id: 'introduction', title: 'Introduction' },
    { id: 'definitions', title: 'Interpretation and Definitions' },
    { id: 'data-collection', title: 'Collecting and Using Your Personal Data' },
    { id: 'data-use', title: 'Use of Your Personal Data' },
  ];

  const handleSectionClick = (sectionId: string) => {
    setActiveSection(sectionId);
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.title}>Caryyati Privacy Policy</div>
      <div className={styles.subtitle}>
        Learn how we collect, use, and protect your personal information to provide a seamless and secure car rental experience.
      </div>

      <div className={styles.contentWrapper}>
        {/* Sidebar Navigation */}
        <div className={styles.sidebar}>
          <div className={styles.sidebarTitle}>Table of Contents</div>
          {sections.map((section) => (
            <div
              key={section.id}
              className={`${styles.sidebarItem} ${activeSection === section.id ? styles.active : ''}`}
              onClick={() => handleSectionClick(section.id)}
            >
              {section.title}
            </div>
          ))}
        </div>

        {/* Main Content */}
        <div className={styles.mainContent}>
          <section id="introduction" className={styles.section}>
            <h2>Introduction</h2>
            <p>Last updated: April 04, 2021</p>
            <p>
              This Privacy Policy outlines our policies and procedures regarding the collection, use, and disclosure of your information when you use our Service. It also informs you about your privacy rights and how the law protects you.
            </p>
            <p>
              We use your personal data to provide and enhance our Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </section>

          <hr className={styles.divider} />

          <section id="definitions" className={styles.section}>
            <h2>Interpretation and Definitions</h2>
            <p>
              Terms with an initial capital letter have specific meanings as defined below, applicable in both singular and plural forms.
            </p>
            <h3>Definitions</h3>
            <ul className={styles.definitionList}>
              <li>
                <strong>Company</strong> (referred to as "the Company", "We", "Us", or "Our") refers to Caryyati, Dubai, UAE.
              </li>
              <li>
                <strong>Service</strong> refers to the Website or the Application or both.
              </li>
              <li>
                <strong>Personal Data</strong> is any information relating to an identified or identifiable individual.
              </li>
              <li>
                <strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service or from its infrastructure.
              </li>
              <li>
                <strong>Cookies</strong> are small files stored on your device.
              </li>
            </ul>
          </section>

          <hr className={styles.divider} />

          <section id="data-collection" className={styles.section}>
            <h2>Collecting and Using Your Personal Data</h2>
            <p>We collect various types of information to provide and improve our Service.</p>
            <h3>Types of Data Collected</h3>
            <p>
              <strong>Personal Data</strong>: While using our Service, we may request personally identifiable information to contact or identify you.
            </p>
            <p>
              <strong>Usage Data</strong>: We may collect information on how the Service is accessed and used.
            </p>
          </section>

          <hr className={styles.divider} />

          <section id="data-use" className={styles.section}>
            <h2>Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className={styles.useList}>
              <li>To provide and maintain our Service</li>
              <li>To notify you about changes to our Service</li>
              <li>To enable participation in interactive features</li>
            </ul>
          </section>
        </div>
      </div>

      <Footer />
    </div>
  );
};

export default PrivacyPolicy;